#!/usr/bin/python
#
# librefmem
#

env = Environment()

src = [ 'alloc.c', 'debug.c' ]

static = env.StaticLibrary('refmem', src, CPPPATH = [ '../include', '.' ])
shared = env.SharedLibrary('refmem', src, CPPPATH = [ '../include', '.' ])

inst = [ static, shared ]

Return('inst')
