#!/usr/bin/python
#
# libcmyth
#

Import('env')

src = [ 'bookmark.c', 'connection.c', 'debug.c', 'event.c',
        'file.c', 'freespace.c', 'keyframe.c', 'mythtv_mysql.c',
        'posmap.c', 'proginfo.c', 'proglist.c', 'rec_num.c', 
        'recorder.c', 'ringbuf.c', 'socket.c', 'timestamp.c',
        'livetv.c', 'mysql_query.c', 'commbreak.c' ]

static = env.StaticLibrary('cmyth', src, CPPPATH = [ '../include', '.' ])
shared = env.SharedLibrary('cmyth', src, CPPPATH = [ '../include', '.' ])

inst = [ static, shared ]

Return('inst')
