#!/usr/bin/python
#
# cmyth apps
#

Import('env')

libs = [ 'cmyth', 'pthread', 'refmem', ]

if not env.GetOption('clean'):
    conf = Configure(env)
    if conf.CheckLib('mysqlclient'):
        libs += [ 'mysqlclient' ]
    env = conf.Finish()

mythfuse = env.Program('mythfuse', 'mythfuse.c',
                       CCFLAGS = ' -D_FILE_OFFSET_BITS=64',
                       CPPPATH = [ '../include' ],
                       LIBS = libs + [ 'fuse' ],
                       LIBPATH = [ '../libcmyth', '../librefmem' ])

mythping = env.Program('mythping', 'mythping.c',
                       CPPPATH = [ '../include' ],
                       LIBS = libs,
                       LIBPATH = [ '../libcmyth', '../librefmem' ])

targets = [ mythping ]

if not env.GetOption('clean'):
    conf = Configure(env)
    if conf.CheckLib('fuse'):
        targets += [ mythfuse ]
    env = conf.Finish()
else:
    targets += [ mythfuse ]

prefix = env['PREFIX']
env.Install(prefix + '/bin', targets)

Return('targets')
